
weapon = {
    "sword": [
        "Zardzewiałe Ostrze",
        "Miecz Rekruta",
        "Stalowy Sztych",
        "Krótki Miecz Strażnika",
        "Ostrze Wędrowca",
        "Miecz Polny",
        "Hartowana Klinga",
        "Żelazny Kieł",
        "Miecz Najemnika",
        "Klinga Pogranicza",
        "Rycerski Sztych",
        "Miecz Srebrzysty",
        "Ostrze Wilka",
        "Klinga Burzowa",
        "Miecz Czystej Stali",
        "Płomienna Klinga",
        "Miecz Lwiego Serca",
        "Ostrze Przysięgi",
        "Klinga Smoczego Oddechu",
        "Miecz Wojny",
        "Srebrny Pogromca",
        "Ostrze Nocy",
        "Miecz Runiczny",
        "Klinga Królewskiego Gwardzisty",
        "Miecz Żaru",
        "Ostrze Burzyciela",
        "Klinga Feniksa",
        "Miecz Honorowy",
        "Szczerbiec Północy",
        "Ostrze Wiecznej Walki",
        "Miecz Smoczej Krwi",
        "Klinga Przeznaczenia",
        "Ostrze Nieugaszone",
        "Miecz Starożytnego Bohatera",
        "Klinga Run Krwi",
        "Ostrze Zagłady",
        "Miecz Niezłomnych",
        "Klinga Wiecznego Ognia",
        "Ostrze Kataklizmu",
        "Miecz Królewski",
        "Klinga Pradawnych",
        "Ostrze Apokalipsy",
        "Miecz Smoczego Władcy",
        "Klinga Czasu",
        "Ostrze Boskiej Sprawiedliwości",
        "Miecz Końca Er",
        "Klinga Absolutu",
        "Ostrze Nieskończoności",
        "Miecz Pierwszego Płomienia",
        "Klinga Boga Wojny"
    ],

    "bow": [
        "Krótki Łuk Myśliwego",
        "Łuk Rekruta",
        "Drewniany Łuk",
        "Łuk Polowy",
        "Łuk Wędrowca",
        "Prosty Łuk Jesionowy",
        "Łuk Strażnika",
        "Wzmocniony Łuk",
        "Łuk Tropiciela",
        "Łuk Zwiadowcy",
        "Łuk Dębowy",
        "Łuk Dalekiego Strzału",
        "Łuk Wilczego Szlaku",
        "Łuk Wiatru",
        "Łuk Precyzji",
        "Łuk Burzowy",
        "Łuk Łowcy Bestii",
        "Łuk Srebrnej Strzały",
        "Łuk Cienia",
        "Łuk Wojenny",
        "Łuk Runiczny",
        "Łuk Feniksa",
        "Łuk Królewskiego Strzelca",
        "Łuk Ognistego Deszczu",
        "Łuk Nocy",
        "Łuk Smoczej Kości",
        "Łuk Przysięgi",
        "Łuk Ducha Lasu",
        "Łuk Burzyciela",
        "Łuk Pradawnych",
        "Łuk Wiecznego Wiatru",
        "Łuk Smoczego Gniewu",
        "Łuk Gwiezdnych Strzał",
        "Łuk Losu",
        "Łuk Kataklizmu",
        "Łuk Krwawego Księżyca",
        "Łuk Króla Północy",
        "Łuk Nieskończonego Lotu",
        "Łuk Boskiego Myśliwego",
        "Łuk Apokalipsy",
        "Łuk Strażnika Światów",
        "Łuk Smoczego Władcy",
        "Łuk Eteru",
        "Łuk Czasu",
        "Łuk Pierwszej Strzały",
        "Łuk Przeznaczenia",
        "Łuk Wiecznej Ciszy",
        "Łuk Absolutu",
        "Łuk Nieskończoności",
        "Łuk Ostatecznego Strzału"
    ],

    "staff": [
        "Drewniana Różdżka",
        "Różdżka Ucznia",
        "Kostur Adepta",
        "Różdżka Iskry",
        "Kostur Wędrownego Maga",
        "Różdżka Skupienia",
        "Kostur Manowy",
        "Różdżka Ognika",
        "Kostur Zaklinacza",
        "Różdżka Wiatru",
        "Kostur Żywiołów",
        "Różdżka Lodu",
        "Kostur Burzy",
        "Różdżka Runiczna",
        "Kostur Maga Wojny",
        "Różdżka Płomieni",
        "Kostur Dusz",
        "Różdżka Cienia",
        "Kostur Tajemnic",
        "Różdżka Energii",
        "Kostur Pradawny",
        "Różdżka Feniksa",
        "Kostur Arkanów",
        "Różdżka Królewskiego Maga",
        "Kostur Żaru",
        "Różdżka Nocy",
        "Kostur Smoczej Magii",
        "Różdżka Przeznaczenia",
        "Kostur Kataklizmu",
        "Różdżka Gwiazd",
        "Kostur Eteru",
        "Różdżka Wiecznej Burzy",
        "Kostur Run Krwi",
        "Różdżka Apokalipsy",
        "Kostur Strażnika Światów",
        "Różdżka Boskiego Ognia",
        "Kostur Czasu",
        "Różdżka Absolutu",
        "Kostur Nieskończoności",
        "Różdżka Pierwszego Maga",
        "Kostur Smoczego Władcy",
        "Różdżka Wiecznej Many",
        "Kostur Kosmosu",
        "Różdżka Pradawnych Bogów",
        "Kostur Rzeczywistości",
        "Różdżka Końca Er",
        "Kostur Stworzenia",
        "Różdżka Nieskończonej Mocy",
        "Kostur Absolutnej Magii",
        "Różdżka Boga Magii"
    ]
}

Rarity = {
    "Normal": [1,20],
    "Rare": [21,40],
    "Epic": [41,60],
    "Legend": [61,80],
    "Hero": [81,100]
}













