Dungeons = {
  "Shadowfang_Crypt": [1,10],
  "Ashen_Hollow": [11,20],
  "Obsidian_Depths": [21,30],
  "Whispering_Catacombs": [31,40],
  "Sunken_Sanctum": [41,50],
  "Frostveil_Cavern": [51,60],
  "Bloodroot_Ruins": [61,70],
  "Eclipse_Vault": [71,80],
  "Grimwatch_Tunnels": [81,90],
  "End_of_All_Realms": [91,100]
}
guilds = [
    "Iron Covenant",
    "Shadow Dominion",
    "Eternal Vanguard",
    "Crimson Order",
    "Frostborn Legion",
    "Nightfall Syndicate",
    "Stormward Alliance",
    "Obsidian Circle",
    "Phoenix Ascendants",
    "Void Reavers",
    "Silver Eclipse",
    "Blackthorn Brotherhood",
    "Astral Sentinels",
    "Bloodbound Pact",
    "Ravenfall Union",
    "Emberwatch",
    "Dawnforged",
    "Grim Horizon",
    "Starfall Collective",
    "Ironclad Oath",
    "Warden Ascension",
    "Netherveil",
    "Ashen Vanguard",
    "Moonshade Guild",
    "Thorned Crown",
    "Celestial Rift",
    "Warborn Syndicate",
    "Feral Dominion",
    "Arcane Resolve",
    "Valiant Exiles",
    "Shadowspire",
    "Runebound Order",
    "Stormbreakers",
    "Ebon Legacy",
    "Last Bastion"
]
