Dungeons = {
  "Shadowfang_Crypt": [1,10],
  "Ashen_Hollow": [11,20],
  "Obsidian_Depths": [21,30],
  "Whispering_Catacombs": [31,40],
  "Sunken_Sanctum": [41,50],
  "Frostveil_Cavern": [51,60],
  "Bloodroot_Ruins": [61,70],
  "Eclipse_Vault": [71,80],
  "Grimwatch_Tunnels": [81,90],
  "End_of_All_Realms": [91,100]
}
guilds = [
    "Iron Covenant",
    "Shadow Dominion",
    "Eternal Vanguard",
    "Crimson Order",
    "Frostborn Legion",
    "Nightfall Syndicate",
    "Stormward Alliance",
    "Obsidian Circle",
    "Phoenix Ascendants",
    "Void Reavers",
    "Silver Eclipse",
    "Blackthorn Brotherhood",
    "Astral Sentinels",
    "Bloodbound Pact",
    "Ravenfall Union",
    "Emberwatch",
    "Dawnforged",
    "Grim Horizon",
    "Starfall Collective",
    "Ironclad Oath",
    "Warden Ascension",
    "Netherveil",
    "Ashen Vanguard",
    "Moonshade Guild",
    "Thorned Crown",
    "Celestial Rift",
    "Warborn Syndicate",
    "Feral Dominion",
    "Arcane Resolve",
    "Valiant Exiles",
    "Shadowspire",
    "Runebound Order",
    "Stormbreakers",
    "Ebon Legacy",
    "Last Bastion"
]


import random

# Lista 100 nazw i żywiołów
pets = [
    ("Mazdak", "Shadow"), ("Izi", "Fire"), ("Kutasos", "Ice"), ("Flim", "Water"), ("Niro", "Plant"),
    ("Zarko", "Wind"), ("Lume", "Electric"), ("Bront", "Earth"), ("Fira", "Light"), ("Vex", "Fire"),
    ("Sora", "Ice"), ("Quill", "Water"), ("Thym", "Plant"), ("Zephyr", "Wind"), ("Volt", "Electric"),
    ("Crag", "Earth"), ("Nyx", "Shadow"), ("Lux", "Light"), ("Pyro", "Fire"), ("Glace", "Ice"),
    ("Aqua", "Water"), ("Fern", "Plant"), ("Gale", "Wind"), ("Spark", "Electric"), ("Boulder", "Earth"),
    ("Shade", "Shadow"), ("Radi", "Light"), ("Ignis", "Fire"), ("Frost", "Ice"), ("Rivu", "Water"),
    ("Moss", "Plant"), ("Breez", "Wind"), ("Charge", "Electric"), ("Stone", "Earth"), ("Umbra", "Shadow"),
    ("Luma", "Light"), ("Ember", "Fire"), ("Crystal", "Ice"), ("Ripple", "Water"), ("Thorn", "Plant"),
    ("Whirl", "Wind"), ("Zap", "Electric"), ("Gravel", "Earth"), ("Dusk", "Shadow"), ("Dawn", "Light"),
    ("Blaze", "Fire"), ("Shiver", "Ice"), ("Stream", "Water"), ("Vine", "Plant"), ("Drift", "Wind"),
    ("Amp", "Electric"), ("Clay", "Earth"), ("Gloom", "Shadow"), ("Halo", "Light"), ("Cinder", "Fire"),
    ("Hail", "Ice"), ("Brook", "Water"), ("Petal", "Plant"), ("Puff", "Wind"), ("Volt", "Electric"),
    ("Rock", "Earth"), ("Obscur", "Shadow"), ("Shine", "Light"), ("Scorch", "Fire"), ("Icicle", "Ice"),
    ("Tide", "Water"), ("Leaf", "Plant"), ("Tornado", "Wind"), ("Lightning", "Electric"), ("Pebble", "Earth"),
    ("Phantom", "Shadow"), ("Glow", "Light"), ("Flare", "Fire"), ("Snow", "Ice"), ("Dew", "Water"),
    ("Sprout", "Plant"), ("Gust", "Wind"), ("Bolt", "Electric"), ("Cliff", "Earth"), ("Wraith", "Shadow"),
    ("Prism", "Light"), ("Kindle", "Fire"), ("Glacier", "Ice"), ("Pool", "Water"), ("Bud", "Plant"),
    ("Sirocco", "Wind"), ("Flash", "Electric"), ("Stone", "Earth"), ("Shade", "Shadow"), ("Beacon", "Light"),
    ("Scald", "Fire"), ("Freeze", "Ice"), ("Current", "Water"), ("Root", "Plant"), ("Whisp", "Wind"),
    ("Surge", "Electric"), ("Rocko", "Earth"), ("Night", "Shadow"), ("Radiant", "Light"), ("Torch", "Fire")
]
pets = [
    {'name': 'Mazdak', 'element': 'Shadow', 'level': 67},
    {'name': 'Izi', 'element': 'Fire', 'level': 30},
    {'name': 'Kutasos', 'element': 'Ice', 'level': 74},
    {'name': 'Flim', 'element': 'Water', 'level': 62},
    {'name': 'Niro', 'element': 'Plant', 'level': 48},
    {'name': 'Zarko', 'element': 'Wind', 'level': 75},
    {'name': 'Lume', 'element': 'Electric', 'level': 39},
    {'name': 'Bront', 'element': 'Earth', 'level': 28},
    {'name': 'Fira', 'element': 'Light', 'level': 66},
    {'name': 'Vex', 'element': 'Fire', 'level': 20},
    {'name': 'Sora', 'element': 'Ice', 'level': 30},
    {'name': 'Quill', 'element': 'Water', 'level': 44},
    {'name': 'Thym', 'element': 'Plant', 'level': 55},
    {'name': 'Zephyr', 'element': 'Wind', 'level': 64},
    {'name': 'Volt', 'element': 'Electric', 'level': 47},
    {'name': 'Crag', 'element': 'Earth', 'level': 84},
    {'name': 'Nyx', 'element': 'Shadow', 'level': 16},
    {'name': 'Lux', 'element': 'Light', 'level': 33},
    {'name': 'Pyro', 'element': 'Fire', 'level': 58},
    {'name': 'Glace', 'element': 'Ice', 'level': 64},
    {'name': 'Aqua', 'element': 'Water', 'level': 37},
    {'name': 'Fern', 'element': 'Plant', 'level': 43},
    {'name': 'Gale', 'element': 'Wind', 'level': 51},
    {'name': 'Spark', 'element': 'Electric', 'level': 36},
    {'name': 'Boulder', 'element': 'Earth', 'level': 32},
    {'name': 'Shade', 'element': 'Shadow', 'level': 48},
    {'name': 'Radi', 'element': 'Light', 'level': 79},
    {'name': 'Ignis', 'element': 'Fire', 'level': 56},
    {'name': 'Frost', 'element': 'Ice', 'level': 51},
    {'name': 'Rivu', 'element': 'Water', 'level': 91},
    {'name': 'Moss', 'element': 'Plant', 'level': 27},
    {'name': 'Breez', 'element': 'Wind', 'level': 79},
    {'name': 'Charge', 'element': 'Electric', 'level': 60},
    {'name': 'Stone', 'element': 'Earth', 'level': 60},
    {'name': 'Umbra', 'element': 'Shadow', 'level': 55},
    {'name': 'Luma', 'element': 'Light', 'level': 58},
    {'name': 'Ember', 'element': 'Fire', 'level': 23},
    {'name': 'Crystal', 'element': 'Ice', 'level': 55},
    {'name': 'Ripple', 'element': 'Water', 'level': 60},
    {'name': 'Thorn', 'element': 'Plant', 'level': 47},
    {'name': 'Whirl', 'element': 'Wind', 'level': 39},
    {'name': 'Zap', 'element': 'Electric', 'level': 21},
    {'name': 'Gravel', 'element': 'Earth', 'level': 34},
    {'name': 'Dusk', 'element': 'Shadow', 'level': 56},
    {'name': 'Dawn', 'element': 'Light', 'level': 36},
    {'name': 'Blaze', 'element': 'Fire', 'level': 53},
    {'name': 'Shiver', 'element': 'Ice', 'level': 30},
    {'name': 'Stream', 'element': 'Water', 'level': 34},
    {'name': 'Vine', 'element': 'Plant', 'level': 63},
    {'name': 'Drift', 'element': 'Wind', 'level': 50},
    {'name': 'Amp', 'element': 'Electric', 'level': 55},
    {'name': 'Clay', 'element': 'Earth', 'level': 55},
    {'name': 'Gloom', 'element': 'Shadow', 'level': 68},
    {'name': 'Halo', 'element': 'Light', 'level': 47},
    {'name': 'Cinder', 'element': 'Fire', 'level': 32},
    {'name': 'Hail', 'element': 'Ice', 'level': 51},
    {'name': 'Brook', 'element': 'Water', 'level': 55},
    {'name': 'Petal', 'element': 'Plant', 'level': 47},
    {'name': 'Puff', 'element': 'Wind', 'level': 57},
    {'name': 'Rock', 'element': 'Earth', 'level': 36},
    {'name': 'Obscur', 'element': 'Shadow', 'level': 35},
    {'name': 'Shine', 'element': 'Light', 'level': 49},
    {'name': 'Scorch', 'element': 'Fire', 'level': 48},
    {'name': 'Icicle', 'element': 'Ice', 'level': 40},
    {'name': 'Tide', 'element': 'Water', 'level': 51},
    {'name': 'Leaf', 'element': 'Plant', 'level': 49},
    {'name': 'Tornado', 'element': 'Wind', 'level': 41},
    {'name': 'Lightning', 'element': 'Electric', 'level': 78},
    {'name': 'Pebble', 'element': 'Earth', 'level': 54},
    {'name': 'Phantom', 'element': 'Shadow', 'level': 54},
    {'name': 'Glow', 'element': 'Light', 'level': 72},
    {'name': 'Flare', 'element': 'Fire', 'level': 63},
    {'name': 'Snow', 'element': 'Ice', 'level': 40},
    {'name': 'Dew', 'element': 'Water', 'level': 83},
    {'name': 'Sprout', 'element': 'Plant', 'level': 34},
    {'name': 'Gust', 'element': 'Wind', 'level': 66},
    {'name': 'Bolt', 'element': 'Electric', 'level': 42},
    {'name': 'Cliff', 'element': 'Earth', 'level': 48},
    {'name': 'Wraith', 'element': 'Shadow', 'level': 44},
    {'name': 'Prism', 'element': 'Light', 'level': 40},
    {'name': 'Kindle', 'element': 'Fire', 'level': 34},
    {'name': 'Glacier', 'element': 'Ice', 'level': 85},
    {'name': 'Pool', 'element': 'Water', 'level': 58},
    {'name': 'Bud', 'element': 'Plant', 'level': 46},
    {'name': 'Sirocco', 'element': 'Wind', 'level': 65},
    {'name': 'Flash', 'element': 'Electric', 'level': 47},
    {'name': 'Beacon', 'element': 'Light', 'level': 54},
    {'name': 'Scald', 'element': 'Fire', 'level': 49},
    {'name': 'Freeze', 'element': 'Ice', 'level': 35},
    {'name': 'Current', 'element': 'Water', 'level': 15},
    {'name': 'Root', 'element': 'Plant', 'level': 62},
    {'name': 'Whisp', 'element': 'Wind', 'level': 49},
    {'name': 'Surge', 'element': 'Electric', 'level': 23},
    {'name': 'Rocko', 'element': 'Earth', 'level': 68},
    {'name': 'Night', 'element': 'Shadow', 'level': 59},
    {'name': 'Radiant', 'element': 'Light', 'level': 34},
    {'name': 'Torch', 'element': 'Fire', 'level': 48}
]
